### PR TITLE
Improvement on README

### PR DESCRIPTION
**Pull request by pajachiet**
- some corrections on the README, like the name of the module, but essentially improvements on the formating
- adding some file to gitignore
- removing config.json, which is specific for each project

### CODE REVIEW

**Comment by MaximeGaudin** [comment]
Thanks @pajachiet for your PR ! It's appreciated here at Hopwork :)

**Comment by MaximeGaudin** [comment]
I released a new version of the tool on PyPi : https://pypi.python.org/pypi/mongo-connector-postgresql/1.1.0

**Comment by pajachiet** [comment]
You're welcome. Thanks a lot for this module. 
We are going to delve into the code a bit further, as we need to create a mapping with a list of string inside a list of objects.

**Comment by MaximeGaudin** [comment]
This feature is already implemented but I surely need to document it properly. I will try to update the documentation this week, stay tuned :)

**Comment by MaximeGaudin** [comment]
@pajachiet And voilà ! https://github.com/Hopwork/mongo-connector-postgresql/commit/a0fdda87bb20b756aea86321f4fa013d1d573c4c
Feel free to open an issue if some parts are unclear

**Comment by pajachiet** [comment]
Thanks a lot Maxime !
I tried with @aureliengervasi to implement your mapping for imbricated arrays.
We think there is an error in the mapping structure that you suggest for this case, as the '_id' field does not exist in 'timeline_posts' and 'timeline_posts_tags'. 
More info on the related [issue](https://github.com/Hopwork/mongo-connector-postgresql/issues/7).

**Pull request merged**
