### PR TITLE
Feature transform

### PR DESCRIPTION
**Pull request by linkdd**
Hello,

We needed a feature to transform fields from MongoDB because we have some foreign keys as DBREF in our data-model.

The feature is pretty simple to use:

 - add a ``transform`` field in your field mapping, pointing to a python function
 - the python function takes a single parameter (the Mongo value) and returns the transformed value

The README has been updated accordingly.

### CODE REVIEW

**Comment by MaximeGaudin** [comment]
Hey ! 

Again this is awesome however even though I am totally for merging this feature, I would like the how implemented differently.

Indeed, one of the thing I like is having control over the connector purely via my mapping(s) file(s). What do you think about using python lambda directly in the mapping. 

For instance : 

    {
       "db": { 
           "transformed_field": {
              "dest": "field",
              "type": "BOOLEAN",
              "transform": "x * 2"
            }
     }

This way, the code can evaluate the lamda (def to_function(s): return eval("lambda x:" + s) and run it to obtain the transformed value ?

What do you think of that @linkdd ?

**Comment by linkdd** [comment]
Okay, but then, I would like to use [RestrictedPython](https://github.com/zopefoundation/RestrictedPython/tree/master/src/RestrictedPython) to sandbox the code that will be evaluated.

**Comment by MaximeGaudin** [comment]
Yeaye that would be awesome !

**Comment by pajachiet** [comment]
Hi guys,
Would that allow to use more advanced functions ? For example regex using python re module.
I had the idea that multiline lambda functions are not possible in Python.

**Comment by MaximeGaudin** [comment]
Hi @pajachiet,
You are right, only simple transformation is possible with the "lamdba in the mapping" method.

Even though I will try to implement externally defined function, I would like the transform to be merged first so we can test drive this before going further.

I will create an issue later for this feature

**Comment by linkdd** [comment]
I may have a solution which takes the best of both worlds:

    "transform": "x + 2"

And:

    "transform": "@package.module.function"

This way, by default we generate a lambda for simple transformations, and allows the user to point to a Python function for more complex ones.

**Comment by linkdd** [comment]
Nooo, ``RestrictedPython`` is'nt available for Python 3 yet ( https://github.com/zopefoundation/RestrictedPython/tree/Python3_update )

:-( I'll have to find another library.

**Comment by linkdd** [comment]
It seems a new version of RestrictedPython is out, handling support of Python3. I will update the branch to support this feature.

**Comment by MaximeGaudin** [comment]
To be honest I am still not a fan of calling external function from the mapping. This connector is not meant to be an ETL and if I can imagine a case where one would want to perform simple operation (such as string  manipulation or format normalization), I don't want too many thing in here.
I will implement the lambda function call with the RetrictedPython sandbox but not the external call. 

Thanks for the contribution though

**Pull request closed without merging**
