### PR TITLE
Add foreign-keys to PostgreSQL schema

### PR DESCRIPTION
**Pull request by linkdd**
Hello,

This pull request adds the foreign key constraints to the table created in PostgreSQL, and refactor the code for insertion to handle nested arrays when the primary key is auto generated.

The update is done by removing the previous entry (``DELETE CASCADE`` is done thanks to the foreign key constraints) and inserting it again.

The code has been done in ``sql_bulk_insert`` and perform only one big request (using the ``WITH`` feature of PostgreSQL and the ``INSERT INTO ... SELECT ... FROM ... RETURNING <primary_key>`` query) instead of multiple requests that would have not fulfill the foreign key constraints.

Unit tests have not yet been updated, so that's why I need the continuous integration trigger.

**NB:** I had an issue with ``_id`` not being ``ObjectId`` resulting in a crash of mongo-connector, it seems to be fixed in a later version of mongo-connector, so I had to update the dependency in both ``requirements.txt`` and ``setup.py``.

### CODE REVIEW

**Comment by linkdd** [comment]
I have finished both functional tests and unit tests on this feature.

It is now mergeable :)

**Comment by aureliengervasi** [comment]
Hi @MaximeGaudin, 

In our current project, we are reaching a point were we need a version of the doc manager with the features added by @linkdd plus some commits added to fix some issues. You can check the [master branch of our fork](https://github.com/pajachiet/mongo-connector-postgresql) for info.

In order to deploy it in our production environment, we have the constrain of using a packaged version of it (via PyPI). Hence, if these PR are not merged, we will have to create a forked package on PyPI as long as these features are not pulled upstream.

What is your opinion on that ? Do you think you will find some time soon to work on those PR (plus one more coming from our repo to add a couple of commits) ?

For info, as we believe this module, associated with other open-source solutions, could be useful to other people, we have been beginning to talk about it. We performed a presentation on PyParis 2017 ([slides here](https://www.slideshare.net/PoleSystematicParisRegion/opensource-analytics-stack-on-mongodb-with-schema-pierrealain-jachiet-and-aurlien-gervasi)) showcasing a complete pipeline and we are considering writing a blog post about it. Of course, we refer to your work in it! :-)

**Comment by pajachiet** [comment]
The most important feature in our current master version is to solve the issue of nested arrays of arrays  https://github.com/Hopwork/mongo-connector-postgresql/issues/7, which are currently impossible to map

**Comment by MaximeGaudin** [comment]
What a nice contribution, thanks @linkdd !
@pajachiet I will make a release once I ran the new version against our data for some days (i.e. next week)

**Comment by JulieRossi** [comment]
Hello @MaximeGaudin, using this feature with two doc managers leads to KeyError here: https://github.com/Hopwork/mongo-connector-postgresql/blob/master/mongo_connector/doc_managers/postgresql_manager.py#L231
To avoid this, the update function should start just like the delete function (https://github.com/Hopwork/mongo-connector-postgresql/blob/master/mongo_connector/doc_managers/postgresql_manager.py#L257) with:
```
if not is_mapped(self.mappings, namespace):
    return
```

**Pull request merged**
